export const languageList = [
  { name: 'English', code: 'en', country: 'US' },
  { name: 'English (UK)', code: 'en-GB', country: 'GB' },
  { name: 'Arabic', code: 'ar', country: 'SA' },
  { name: 'French', code: 'fr', country: 'FR' },
  { name: 'French (Canada)', code: 'fr-CA', country: 'CA' },
  { name: 'German', code: 'de', country: 'DE' },
  { name: 'Hindi', code: 'hi', country: 'IN' },
  { name: 'Indonesian', code: 'id', country: 'ID' },
  { name: 'Italian', code: 'it', country: 'IT' },
  { name: 'Japanese', code: 'ja', country: 'JP' },
  { name: 'Korean', code: 'ko', country: 'KR' },
  { name: 'Chinese (Simplified)', code: 'zh', country: 'CN' },
  { name: 'Chinese (Traditional)', code: 'zh-TW', country: 'TW' },
  { name: 'Português (Brazil)', code: 'pt-BR', country: 'BR' },
  { name: 'Português (Portugal)', code: 'pt', country: 'PT' },
  { name: 'Russian', code: 'ru', country: 'RU' },
  { name: 'Spanish', code: 'es', country: 'ES' },
  { name: 'Spanish (Latin America)', code: 'es-419', country: 'MX' },
  { name: 'Turkish', code: 'tr', country: 'TR' },
  { name: 'Afrikaans', code: 'af', country: 'ZA' },
  { name: 'Albanian', code: 'sq', country: 'AL' },
  { name: 'Amharic', code: 'am', country: 'ET' },
  { name: 'Armenian', code: 'hy', country: 'AM' },
  { name: 'Azerbaijani', code: 'az', country: 'AZ' },
  { name: 'Basque', code: 'eu', country: 'ES' },
  { name: 'Belarusian', code: 'be', country: 'BY' },
  { name: 'Bengali', code: 'bn', country: 'BD' },
  { name: 'Bosnian', code: 'bs', country: 'BA' },
  { name: 'Bulgarian', code: 'bg', country: 'BG' },
  { name: 'Catalan', code: 'ca', country: 'ES' },
  { name: 'Cebuano', code: 'ceb', country: 'PH' },
  { name: 'Croatian', code: 'hr', country: 'HR' },
  { name: 'Czech', code: 'cs', country: 'CZ' },
  { name: 'Danish', code: 'da', country: 'DK' },
  { name: 'Dutch', code: 'nl', country: 'NL' },
  { name: 'Estonian', code: 'et', country: 'EE' },
  { name: 'Finnish', code: 'fi', country: 'FI' },
  { name: 'Galician', code: 'gl', country: 'ES' },
  { name: 'Georgian', code: 'ka', country: 'GE' },
  { name: 'Greek', code: 'el', country: 'GR' },
  { name: 'Gujarati', code: 'gu', country: 'IN' },
  { name: 'Hausa', code: 'ha', country: 'NG' },
  { name: 'Hebrew', code: 'he', country: 'IL' },
  { name: 'Hungarian', code: 'hu', country: 'HU' },
  { name: 'Icelandic', code: 'is', country: 'IS' },
  { name: 'Igbo', code: 'ig', country: 'NG' },
  { name: 'Irish', code: 'ga', country: 'IE' },
  { name: 'Javanese', code: 'jw', country: 'ID' },
  { name: 'Kannada', code: 'kn', country: 'IN' },
  { name: 'Kazakh', code: 'kk', country: 'KZ' },
  { name: 'Khmer', code: 'km', country: 'KH' },
  { name: 'Kurdish', code: 'ku', country: 'IQ' },
  { name: 'Kyrgyz', code: 'ky', country: 'KG' },
  { name: 'Lao', code: 'lo', country: 'LA' },
  { name: 'Latvian', code: 'lv', country: 'LV' },
  { name: 'Lithuanian', code: 'lt', country: 'LT' },
  { name: 'Luxembourgish', code: 'lb', country: 'LU' },
  { name: 'Macedonian', code: 'mk', country: 'MK' },
  { name: 'Malagasy', code: 'mg', country: 'MG' },
  { name: 'Malay', code: 'ms', country: 'MY' },
  { name: 'Malayalam', code: 'ml', country: 'IN' },
  { name: 'Maltese', code: 'mt', country: 'MT' },
  { name: 'Maori', code: 'mi', country: 'NZ' },
  { name: 'Marathi', code: 'mr', country: 'IN' },
  { name: 'Mongolian', code: 'mn', country: 'MN' },
  { name: 'Myanmar (Burmese)', code: 'my', country: 'MM' },
  { name: 'Nepali', code: 'ne', country: 'NP' },
  { name: 'Norwegian', code: 'no', country: 'NO' },
  { name: 'Nyanja', code: 'ny', country: 'MW' },
  { name: 'Pashto', code: 'ps', country: 'AF' },
  { name: 'Persian', code: 'fa', country: 'IR' },
  { name: 'Polish', code: 'pl', country: 'PL' },
  { name: 'Punjabi', code: 'pa', country: 'IN' },
  { name: 'Romanian', code: 'ro', country: 'RO' },
  { name: 'Samoan', code: 'sm', country: 'WS' },
  { name: 'Scots Gaelic', code: 'gd', country: 'GB' },
  { name: 'Serbian', code: 'sr', country: 'RS' },
  { name: 'Sesotho', code: 'st', country: 'LS' },
  { name: 'Shona', code: 'sn', country: 'ZW' },
  { name: 'Sindhi', code: 'sd', country: 'PK' },
  { name: 'Sinhala', code: 'si', country: 'LK' },
  { name: 'Slovak', code: 'sk', country: 'SK' },
  { name: 'Slovenian', code: 'sl', country: 'SI' },
  { name: 'Somali', code: 'so', country: 'SO' },
  { name: 'Sundanese', code: 'su', country: 'ID' },
  { name: 'Swahili', code: 'sw', country: 'TZ' },
  { name: 'Swedish', code: 'sv', country: 'SE' },
  { name: 'Tagalog', code: 'tl', country: 'PH' },
  { name: 'Tajik', code: 'tg', country: 'TJ' },
  { name: 'Tamil', code: 'ta', country: 'IN' },
  { name: 'Tatar', code: 'tt', country: 'RU' },
  { name: 'Telugu', code: 'te', country: 'IN' },
  { name: 'Thai', code: 'th', country: 'TH' },
  { name: 'Ukrainian', code: 'uk', country: 'UA' },
  { name: 'Urdu', code: 'ur', country: 'PK' },
  { name: 'Uzbek', code: 'uz', country: 'UZ' },
  { name: 'Vietnamese', code: 'vi', country: 'VN' },
  { name: 'Welsh', code: 'cy', country: 'GB' },
  { name: 'Xhosa', code: 'xh', country: 'ZA' },
  { name: 'Yiddish', code: 'yi', country: 'IL' },
  { name: 'Yoruba', code: 'yo', country: 'NG' },
  { name: 'Zulu', code: 'zu', country: 'ZA' },
];
